version: "3.9"
services:

  achat:
    container_name: achat_container
    image: "mekniiemna/achat_img"
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/achat_opsTest?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    depends_on:
      -  db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql


  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"


volumes:
  db:











