version: "3.9"
services:

  achat:
    container_name: achat_container
    image: "mekniiemna/achat_img"
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      -  db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql


volumes:
  db:











